name: 'Lint PR title preview (current branch, ignoreLabels enabled)'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

permissions:
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@main
      - uses: meta-introspector/setup-node@main
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
