name: 'Release'
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@main
      - uses: meta-introspector/setup-node@main
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
